# *************************************************************************
# **  Copyright (c) 2024 CentraleSupélec & EDF.
# **  All rights reserved. This program and the accompanying materials
# **  are made available under the terms of the Eclipse Public License v2.0
# **  which accompanies this distribution, and is available at
# **  https://www.eclipse.org/legal/epl-v20.html
# ** 
# **  This file is part of the RiseClipse tool
# **  
# **  Contributors:
# **      Computer Science Department, CentraleSupélec
# **      EDF R&D
# **  Contacts:
# **      dominique.marcadet@centralesupelec.fr
# **      aurelie.dehouck-neveu@edf.fr
# **  Web site:
# **      https://riseclipse.github.io
# *************************************************************************

name: Build launcher documentation, deploy it on riseclipse.github.io

on: workflow_dispatch

jobs:
  build-python-launcher-docs:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout ${{ github.event.repository.name }}
      uses: actions/checkout@v4
      with:
        path: ${{ github.event.repository.name }}

    - name: Checkout riseclipse-temporary
      uses: actions/checkout@v4
      with:
        repository: riseclipse/riseclipse-temporary
        path: riseclipse-temporary
        ref: master

    - name: Install Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
      
    - name: Install dependencies
      run: |
        pip install sphinx sphinx_rtd_theme pandas
        
    - name: Sphinx build
      run: |
        cd ${{ github.event.repository.name }}/fr.centralesupelec.edf.riseclipse.python.launcher/docs
        make html
        touch _build/html/.nojekyll

    - name: Deploy on riseclipse.github.io
      - uses: cpina/github-action-push-to-another-repository@main
        env:
          SSH_DEPLOY_KEY: ${{ secrets.SSH_DEPLOY_KEY }}
        with:
          source-directory: '_build/html'
          destination-github-username: 'riseclipse'
          destination-repository-name: 'riseclipse-temporary'
          user-email: riseclipse@gmail.com
          target-branch: master
          target-directory: python-launcher-docs
